[package]
name = "codesign-bin"
version = "0.1.0"
authors = ["Kjartan F. Kvamme <forbjok@gmail.com>"]

[[bin]]
name = "codesign"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "~0.4.0"
clap = "~2.29.1"
fern = "~0.5.2"
log = "~0.4.1"
codesign = {path = "../lib"}
