[package]
name = "codesign"
version = "0.1.0"
authors = ["Kjartan F. Kvamme <forbjok@gmail.com>"]
description = "Microsoft code signing library for Rust"

[dependencies]
bitness = "~0.2.0"
chrono = "~0.4.0"
clap = "~2.29.1"
fern = "~0.5.2"
log = "~0.4.1"
winreg = "~0.5.0"
